dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  - bash
  - networking-terms
  - python
  - words
  - "!aws"
  - "!backwards-compatibility"
  - "!cryptocurrencies"
  - "!cpp"
ignorePaths:
  # All dot files in the root
  - \.*
  # This file
  - cspell.config.yaml
  # The mypy configuration file
  - mypy.ini
  # The shared file for tool configuration
  - pyproject.toml
  # requirements files
  - .config/requirements*
  - requirements.txt
  # The tox configuration file
  - tox.ini
  # Sample tox configurations
  - docs/*.ini
  - mkdocs.yml

languageSettings:
  - languageId: python
    allowCompoundWords: false
