---
dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  - bash
  - networking-terms
  - python
  - words
  - "!aws"
  - "!backwards-compatibility"
  - "!cryptocurrencies"
  - "!cpp"
useGitignore: true
ignorePaths:
  - "**/.gitignore*"
  - .vscode/extensions.json
  - .vscode/settings.json
  - _readthedocs
  - build
  - coverage.lcov
  - cspell.config.yaml
  - junit.xml
  - site
# - mkdocs.yml
ignoreWords:
  - adoc
  - CAP_MKNOD
  - CMDB
  - equalto
  - lineinfile
  - SSOT
  - SSOTs
  - autorefs
  - commitlint
  - dists
  - docstrings
  - envrc
  - facelessuser
  - fontawesome
  - htmlproofer
  - inlinehilite
  - junitxml
  - linenums
  - loglevel
  - magiclink
  - pkgs
  - posargs
  - pymdownx
  - pypa
  - seccomp
  - sonarlint
  - superfences
  - triggertaskonsave
  - userns
suggestWords:
  - alwayscopy->always_copy
  - basepython->base_python
  - changedir->change_dir
  - env_log_dir->env_log_dir
  - envbindir->env_bin_dir
  - envdir->env_dir
  - envlist->env_list
  - envname->env_name
  - envpython->env_python
  - envsitepackagesdir->env_site_packages_dir
  - envtmpdir->env_tmp_dir
  - ignore_basepython_conflict->ignore_base_python_conflict
  - isolated_build_env->package_env
  - min_version->deprecated-use-requires
  - minversion ->deprecated-use-requires
  - passenv->pass_env
  - setenv->set_env
  - setupdir->package_root
  - sitepackages->system_site_packages
  - skipsdist->no_package
  - toxinidir->tox_root
  - "toxworkdir->work_dir"
  - usedevelop->use_develop
languageSettings:
  - languageId: python
    allowCompoundWords: false
  - languageId: toml
    allowCompoundWords: false
    ignoreWords:
      - showlocals
      - xunit
      - norecursedirs
      - tomlsort
